### ISSUE TITLE
visual feedback is streched

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Time-To-Learn#15]
when i press the red/green feedback button there's normally a brief flicker of red / green. that one used to cover all the area above the bottom button and the center of the screen. now it's not, and this is visually disturbing. 

you can observe this in the following movie: 
https://www.dropbox.com/s/14vri0d0tn2xrzf/VID_20170613_094534.mp4?dl=0

i think you should be able to replicate in the web simulator.

**Comment by mircealungu** [comment]
just in case the movie is not clear enough:

<img width="620" alt="screenshot 2017-06-13 09 52 05" src="https://user-images.githubusercontent.com/464519/27071625-032c97c8-501e-11e7-8e85-7b5be10da0e4.png">

**Comment by yarchiT** [comment]
![image](https://user-images.githubusercontent.com/17945809/27084169-2b1091ea-504b-11e7-9cfd-758424ba1688.png)

fixed
