### ISSUE TITLE
switching actions

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Time-To-Learn#16]
dear people,

after playing a bit with the watch face today, i think it would be more natural to switch the actions that happen on the bottom button and the click of the word. 

why?
- when i click on the word, i'm interacting with that space between the word and the button. and it is only natural that that space would change... thus it would feel more natural if touching that space i change it and make the translation appear. 

do you see what i mean? 
do you agree?

**Comment by yarchiT** [comment]
yeah, its indeed more natural.
we'll fix it
